name: build and publish container

on:
  push:
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'main'

env:
  IMAGE_NAME: ${{ github.repository }}

jobs:
  release-container:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - id: lower-repo
        shell: pwsh
        run: |
          "::set-output name=repository_owner::$($env:GITHUB_REPOSITORY_OWNER.ToLowerInvariant())"

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ steps.lower-repo.outputs.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Install ko 
        uses: imjasonh/setup-ko@v0.7
      
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: cs-mikrotik-bouncer
          sep-tags: ","
          sep-labels: ","
          tags: |
            type=semver,pattern=v{{version}}
            type=semver,pattern=v{{major}}.{{minor}}
            type=semver,pattern=v{{major}}

      
      - name: Build and Push to GHCR with ko
        env:
          KO_DOCKER_REPO: ghcr.io/${{ steps.lower-repo.outputs.repository_owner }}
          TAGS: ${{ steps.meta.outputs.tags }}
          LABELS: ${{ steps.meta.outputs.labels }}
          PLATFORMS: linux/amd64,linux/arm64,linux/arm
        run: |
          PTAGS=`echo $TAGS | sed 's/cs-mikrotik-bouncer://g'`
          export SOURCE_DATE_EPOCH=$(date +%s)
          ko build -B --image-label "$LABELS" -t "$PTAGS" --platform=$PLATFORMS .
